services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      JWT_SECRET: mysecret
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres?schema=public
      HOST: http://backend
      NODE_ENV: development
      PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    environment:
      REACT_APP_API: "http://localhost:4000/"
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
